apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro2
  template:
    metadata:
      labels:
        app: micro2
    spec:
      containers:
      - name: micro2
        image: proy-micro2:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
