spring:
  kafka:
    bootstrap-servers: "localhost:9092"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microspractice
    username: root
    password: 211772809
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: "kafka-practice-2"

server:
  port: 8083

exampleValue: "scene"


